### ISSUE TITLE
Guide not deployed anymore

### ISSUE THREAD

**Issue by julianoes** [Dronecode/camera-manager-docs#33]
It looks like the deployed version and this git repository are out of sync. The last deployed update was 2018-06-19, and the latest PR merged on 2018-11-19.

Basically, as I go through the guide I find mistakes, then I want to fix them, just to find out that they are already fixed :smile: .

**Comment by hamishwillee** [comment]
I'd forgotten about this.

The repo is hosted on Dronecode org which can only use the new style gitbook (not suitable for us). 
So instead I forked to my org and actually publish that using gitbook legacy system: https://github.com/hamishwillee/camera-manager-docs

This didn't matter previously because I was regularly pushing changes across but not doing so much work now. I had hoped we'd be able to sort this out in some other way. For now I have taken the latest changes across and set up a notification to remind me when a push occurs.

Any ideas how to automate a push from master repo to https://github.com/hamishwillee/camera-manager-docs? Another option is for DanA to set up a self hosted system. But as I'm still waiting on the PX4 user guide first we might just live with this for a while.
